/* Seed Data for BizDive 2.0 */
-- Enable UUID extension if not exists
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Update Table Schema to have default UUID if not exists (Optional safety)
ALTER TABLE questions ALTER COLUMN id SET DEFAULT gen_random_uuid();

TRUNCATE TABLE questions RESTART IDENTITY CASCADE;

INSERT INTO questions (id, category, dimension, content, score_weight, mapping_code) VALUES
(gen_random_uuid(), 'common', 'D1', '내 아이디어를 좋아할 사람들이 전국에 몇 명인지 믿을 만한 통계로 계산해봤다.', 3, NULL),
(gen_random_uuid(), 'common', 'D1', '목표 시장 진입을 위한 구체적인 일정과 손익분기점(BEP)을 고려한 자금 운용 계획이 있다.', 3.5, NULL),
(gen_random_uuid(), 'common', 'D1', '이미 비슷한 서비스를 하는 사람들이 놓치고 있는 ''고객의 진짜 불만''이 무엇인지 정확히 안다.', 3.5, NULL),
(gen_random_uuid(), 'common', 'D2', '내가 겪었거나 오랫동안 관찰해온 경험을 바탕으로, 대표자 본인이 가장 잘 해결할 수 있는 문제인가?', 5, NULL),
(gen_random_uuid(), 'common', 'D2', '이 문제가 해결되었을 때, 고객의 삶이 개선되며 우리 사회에 어떤 긍정적인 변화(ESG)를 주는지 설명할 수 있다.', 3.5, NULL),
(gen_random_uuid(), 'common', 'D2', '기존 해결 방식이 고객의 문제를 왜 완벽히 해결하지 못하는지 그 근본적인 한계를 명확히 알고 있다.', 3.5, NULL),
(gen_random_uuid(), 'common', 'D3', '경쟁사 대비 우리 제품이 가진 확실한 차별점(UVP) 3가지를 1분 안에 설명할 수 있다.', 4, NULL),
(gen_random_uuid(), 'common', 'D3', '고객이 우리 서비스를 처음 접하고 결제하기까지의 모든 과정(User Journey)을 그림으로 그릴 수 있다.', 3.5, NULL),
(gen_random_uuid(), 'common', 'D3', '대기업이나 경쟁자가 우리를 쉽게 따라 하지 못하게 막을 ''방어막(특허, 데이터, 영업비밀 등)''이 있다.', 3.5, NULL),
(gen_random_uuid(), 'common', 'D4', '대표자인 나는 이 아이템을 끝까지 완수할 수 있는 전문성(전공, 경력)이나 남다른 경험을 보유하고 있다.', 5, NULL),
(gen_random_uuid(), 'common', 'D4', '매출, 손익분기점(BEP), 자금 흐름 등 우리 회사의 생존을 결정짓는 핵심 재무 지표를 직접 설명할 수 있다.', 4.5, NULL),
(gen_random_uuid(), 'common', 'D4', '우리 팀에 부족한 역량(개발, 마케팅 등)이 무엇인지 알고, 이를 보완할 채용 계획이나 파트너가 있다.', 4, NULL),
(gen_random_uuid(), 'common', 'D5', '아이디어를 실제 제품으로 구현하기 위해 필요한 핵심 기술과 장비, 공정 리스트를 명확히 알고 있다.', 4.5, NULL),
(gen_random_uuid(), 'common', 'D5', '현재 우리의 개발 단계(TRL)를 객관적으로 정의하고, 다음 단계로 가기 위한 기술적 난제를 파악했다.', 4, NULL),
(gen_random_uuid(), 'common', 'D5', '우리가 보유한 기술이나 데이터가 경쟁사보다 우위에 있음을 증명할 객관적 자료(특허, 인증 등)가 있다.', 3.5, NULL),
(gen_random_uuid(), 'common', 'D6', '고객이 제품을 받고 돈을 지불하는 과정이 복잡하지 않고 직관적인 거래 구조로 설계되어 있다.', 4.5, NULL),
(gen_random_uuid(), 'common', 'D6', '제품 하나를 팔았을 때 남는 이익(공헌이익)이 얼마인지 알며, 팔수록 이익이 커지는 구조인가?', 4, NULL),
(gen_random_uuid(), 'common', 'D6', '고객이 한 번 사고 끝나는 것이 아니라, 지속적으로 재구매하거나 구독하게 만들 ''Lock-in 장치''가 있다.', 3.5, NULL),
(gen_random_uuid(), 'common', 'D7', '한 번 구매한 고객이 2번째, 3번째 구매로 이어지는 ''재구매 연결고리''가 제품 내에 심어져 있다.', 5, NULL),
(gen_random_uuid(), 'common', 'D7', '신규 고객 유입 대비 ''생존 비율(Retention Rate)''을 핵심 경쟁력 지표로 관리하고 있다.', 4.5, NULL),
(gen_random_uuid(), 'common', 'D7', '충성 고객이 주변 지인에게 우리 제품을 자발적으로 추천하는 ''바이럴 루프''가 작동하는가?', 4, NULL),
(gen_random_uuid(), 'stage', 'D1', '불특정 다수가 아니라, 내가 지금 당장 만나서 제안할 수 있는 구체적인 집단이나 장소(거점)가 정해져 있다.', 3, 'P'),
(gen_random_uuid(), 'stage', 'D1', '왜 하필 ''지금'' 이 사업을 해야 하는지, 시장의 변화(법규, 트렌드 등)를 근거로 타이밍을 설명할 수 있다.', 2.5, 'P'),
(gen_random_uuid(), 'stage', 'D1', '사업 개시 후 1년 안에 달성할 현실적인 목표치(매출, 유저 수)를 산출하고 근거를 가지고 있다.', 3.5, 'P'),
(gen_random_uuid(), 'stage', 'D2', '책상 앞 상상이 아니라, 잠재 고객 10명 이상을 직접 인터뷰하여 문제의 심각성을 확인했다.', 4.5, 'P'),
(gen_random_uuid(), 'stage', 'D2', '고객이 우리 서비스를 가장 절실하게 필요로 하는 상황(Context)과 시점을 구체적으로 묘사할 수 있다.', 3.5, 'P'),
(gen_random_uuid(), 'stage', 'D2', '고객이 이 문제를 해결하기 위해 현재 쓰고 있는 비용(돈, 시간, 노력)이 얼마나 큰지 파악했다.', 3.5, 'P'),
(gen_random_uuid(), 'stage', 'D3', '개발자가 아니더라도 이해할 수 있는 수준의 시각적인 시제품(Mock-up)이나 서비스 흐름도를 그려두었다.', 3, 'P'),
(gen_random_uuid(), 'stage', 'D3', '고객이 익숙한 기존 방식을 버리고 우리 제품으로 갈아탈 만한 강력한 이유(Switching Cost 극복)를 정의했다.', 3, 'P'),
(gen_random_uuid(), 'stage', 'D3', '우리 서비스의 이름과 로고가 고객에게 전달하려는 핵심 메시지와 잘 연결되어 있다.', 2.5, 'P'),
(gen_random_uuid(), 'stage', 'D4', '이 아이템을 사업화하는 데 있어 대표자인 내가 가진 ''경험, 인적 네트워크, 보유 자금''이 핵심 경쟁력이라 확신한다.', 4, 'P'),
(gen_random_uuid(), 'stage', 'D4', '좋은 제품을 넘어, 지속 가능한 기업으로 키우기 위한 ''경영의 3요소(사람, 돈, 시스템)''를 이해하고 준비하고 있다.', 3.5, 'P'),
(gen_random_uuid(), 'stage', 'D4', '향후 발생할 다양한 관계(직원, 고객 등)에서 ''계약서 작성''의 중요성을 알고, 핵심 조항들을 이해하고 있다.', 3.5, 'P'),
(gen_random_uuid(), 'stage', 'D5', '직접 개발할지 외주를 줄지 결정했으며, 외주 용역 관리(RFP 작성 등)를 위한 최소한의 지식이나 조력자가 있다.', 3.5, 'P'),
(gen_random_uuid(), 'stage', 'D5', '제품 출시 전 반드시 획득해야 할 인증(KC 등)이나 법적 허가 사항을 리스트업하고 비용/기간을 파악했다.', 3, 'P'),
(gen_random_uuid(), 'stage', 'D5', '아이디어 보호를 위해 특허 출원, 상표권 등록 등을 진행했거나 구체적인 출원 계획을 가지고 있다.', 3, 'P'),
(gen_random_uuid(), 'stage', 'D6', '실제 제품이 나오기 전, 고객에게 구매 의향(LOI)이나 사전 예약을 받아 유료화 가능성을 타진해 보았다.', 4, 'P'),
(gen_random_uuid(), 'stage', 'D6', '제품 1개를 만드는 데 들어가는 직접비와 고정비를 추산해보고, 손해 보지 않는 최소 판매량을 알고 있다.', 3.5, 'P'),
(gen_random_uuid(), 'stage', 'D6', '제품 완성 직후 입점하거나 판매할 수 있는 첫 번째 유통 채널(First Channel)이 확정되어 있다.', 3, 'P'),
(gen_random_uuid(), 'stage', 'D7', '사업의 성공 여부를 판단할 핵심 지표(KPI) 1~2가지를 설정하고 이를 측정할 방법이 있다.', 3.5, 'P'),
(gen_random_uuid(), 'stage', 'D7', '제품 출시까지 자금이 얼마나 필요한지 정확히 알며, 자금 소진 후의 ''후속 자금 조달 계획(생존 전략)''이 있다.', 4, 'P'),
(gen_random_uuid(), 'stage', 'D7', '초기 고객의 불만이나 요구사항을 제품에 즉시 반영하여 개선할 수 있는 상시 소통 채널(VOC)을 설계했다.', 3.5, 'P'),
(gen_random_uuid(), 'stage', 'D1', '초기 구매 고객들의 공통된 특성(Demographics/Interest)을 데이터로 정의했다.', 3.5, 'E'),
(gen_random_uuid(), 'stage', 'D1', '현재 시장 성장 속도에 맞춰 우리 회사의 매출도 동반 성장하고 있는가?', 3.5, 'E'),
(gen_random_uuid(), 'stage', 'D1', '경쟁사들이 놓치고 있는 빈틈을 공략하여 초기 시장 점유율을 뺏어오고 있다.', 3, 'E'),
(gen_random_uuid(), 'stage', 'D2', '제품 출시 후 접수된 고객 불만(VOC)을 분석하여 문제 정의를 수정한 적이 있다.', 4, 'E'),
(gen_random_uuid(), 'stage', 'D2', '우리가 해결하는 문제가 고객에게 ''없으면 안 되는 것(Must have)''으로 인식된다.', 4.5, 'E'),
(gen_random_uuid(), 'stage', 'D2', '현장에서 발견한 새로운 기회로 사업 방향을 전환(Pivot)할 유연성이 있다.', 3.5, 'E'),
(gen_random_uuid(), 'stage', 'D3', '사용자 편의성(UI/UX) 개선을 위한 A/B 테스트를 정기적으로 수행한다.', 3.5, 'E'),
(gen_random_uuid(), 'stage', 'D3', '실제 고객들이 꼽는 ''우리 제품만의 한 끗(Killer Feature)''이 무엇인지 안다.', 4, 'E'),
(gen_random_uuid(), 'stage', 'D3', '자발적으로 홍보해주는 핵심 고객군(Core User)이 형성되었다.', 3.5, 'E'),
(gen_random_uuid(), 'stage', 'D4', '업무 효율화(1인) 또는 명확한 R&R(팀)을 통해 업무 중복이나 공백을 없앴다.', 4, 'E'),
(gen_random_uuid(), 'stage', 'D4', '초기 자금 소진 속도(Burn Rate)를 관리하며, 매월 손익 현황을 직접 챙긴다.', 4.5, 'E'),
(gen_random_uuid(), 'stage', 'D4', '직원 채용, 용역 계약 등에서 발생할 법적 리스크를 검토한 표준 계약서가 있다.', 4, 'E'),
(gen_random_uuid(), 'stage', 'D5', '제품 불량이나 버그를 즉시 수정할 수 있는 기술 대응 체계가 갖춰져 있다.', 4, 'E'),
(gen_random_uuid(), 'stage', 'D5', '핵심 기술이나 브랜드 보호를 위해 특허 등록이나 상표권 확보를 완료했다.', 3.5, 'E'),
(gen_random_uuid(), 'stage', 'D5', '사용자/주문 증가에 대비해 서버 증설이나 생산 확장 준비를 시작했다.', 3.5, 'E'),
(gen_random_uuid(), 'stage', 'D6', '무료 체험 후 정상 가격으로 결제하는 전환율(Conversion Rate)이 목표에 도달했다.', 4, 'E'),
(gen_random_uuid(), 'stage', 'D6', '제품 1개 판매 시 마케팅비 등을 제외하고도 이익이 남는 구조를 달성했다.', 4.5, 'E'),
(gen_random_uuid(), 'stage', 'D6', '재구매율(Retention)이 전월 대비 상승하거나 안정적 수준을 유지한다.', 4, 'E'),
(gen_random_uuid(), 'stage', 'D7', '고객 획득 비용(CAC)보다 고객 생애 가치(LTV)가 3배 이상 높거나 개선 중이다.', 4.5, 'E'),
(gen_random_uuid(), 'stage', 'D7', 'Series A 투자 유치나 TIPS 도전을 위한 구체적인 마일스톤이 있다.', 4, 'E'),
(gen_random_uuid(), 'stage', 'D7', '고객의 리뷰나 추천을 유도하여 마케팅 비용을 낮추는 바이럴 구조가 작동한다.', 3.5, 'E'),
(gen_random_uuid(), 'stage', 'D1', '1차 타겟 시장을 넘어, 인접 시장이나 해외 시장으로 진출하기 위한 조사가 끝났다.', 3.5, 'V'),
(gen_random_uuid(), 'stage', 'D1', '전체 시장 점유율(M/S)을 높이기 위해 경쟁사 고객을 뺏어올 공격적 전략이 있다.', 4, 'V'),
(gen_random_uuid(), 'stage', 'D1', '시장의 트렌드 변화에 맞춰 신규 비즈니스 기회를 선제적으로 포착하고 있다.', 3, 'V'),
(gen_random_uuid(), 'stage', 'D2', '대중적(Mass) 고객들이 겪는 더 넓고 보편적인 문제를 해결하기 위해 범위를 확장했다.', 3.5, 'V'),
(gen_random_uuid(), 'stage', 'D2', '사회적 책임(ESG)을 요구하는 시장 목소리에 맞춰 공익적 가치를 강화하고 있다.', 3.5, 'V'),
(gen_random_uuid(), 'stage', 'D2', '고객 데이터 분석을 통해 개인화된 문제 해결(Personalization) 솔루션을 제공한다.', 4, 'V'),
(gen_random_uuid(), 'stage', 'D3', '제품 라인업(Line-up) 확장이나 파생 서비스를 통해 고객 가치를 극대화하고 있다.', 3.5, 'V'),
(gen_random_uuid(), 'stage', 'D3', '브랜드 파워만으로도 고객이 우리 제품을 선택할 만큼 인지도와 신뢰도가 구축되었다.', 4, 'V'),
(gen_random_uuid(), 'stage', 'D3', '경쟁사의 모방을 원천 차단할 기술 장벽이나 데이터 해자(Moat)를 구축했다.', 4.5, 'V'),
(gen_random_uuid(), 'stage', 'D4', '대표자의 권한을 C-Level 임원이나 중간 관리자에게 위임하여 시스템 경영을 한다.', 4.5, 'V'),
(gen_random_uuid(), 'stage', 'D4', '우수 인재 유지를 위한 스톡옵션, 성과급 등 보상 체계와 조직 문화가 정립되었다.', 4, 'V'),
(gen_random_uuid(), 'stage', 'D4', '투자자(VC)에게 경영 성과를 투명하게 보고할 수 있는 IR 및 재무 보고 체계가 있다.', 3.5, 'V'),
(gen_random_uuid(), 'stage', 'D5', '급격한 트래픽/주문 증가에도 안정적인 대규모 인프라 운영 능력을 확보했다.', 4, 'V'),
(gen_random_uuid(), 'stage', 'D5', '기업부설연구소나 R&D 전담 부서를 통해 원천 기술 확보 및 고도화를 지속한다.', 4, 'V'),
(gen_random_uuid(), 'stage', 'D5', '고객 데이터를 자산화하고, 보호하기 위한 정보보안 인증(ISMS 등)을 갖췄다.', 3.5, 'V'),
(gen_random_uuid(), 'stage', 'D6', '규모의 경제를 통해 원가율을 획기적으로 낮추거나 운영 효율을 높여 이익을 낸다.', 4.5, 'V'),
(gen_random_uuid(), 'stage', 'D6', '구독, 수수료, 데이터 판매 등 수익 모델 다각화를 통해 매출 안정성을 높였다.', 4, 'V'),
(gen_random_uuid(), 'stage', 'D6', '파트너사나 공급망과 협력하여 수익을 공유하고 상생하는 생태계를 만들고 있다.', 3.5, 'V'),
(gen_random_uuid(), 'stage', 'D7', '마케팅 자동화(CRM)나 AI 도구를 도입하여 고객 관리 및 성장 효율을 극대화한다.', 4, 'V'),
(gen_random_uuid(), 'stage', 'D7', '대규모 자금 조달(Series B/C)이나 M&A를 통한 비유기적 성장을 고려한다.', 4, 'V'),
(gen_random_uuid(), 'stage', 'D7', '글로벌 표준에 맞는 ESG 경영 지표를 도입하고, 성장 전략의 일부로 활용한다.', 3.5, 'V'),
(gen_random_uuid(), 'stage', 'D1', '기존 주력 시장의 포화에 대비해 완전히 새로운 신규 시장을 개척하고 있다.', 4, 'M'),
(gen_random_uuid(), 'stage', 'D1', '급변하는 환경에서 도태되지 않기 위해 디지털 전환(DX)이나 업의 재정의를 시도한다.', 4.5, 'M'),
(gen_random_uuid(), 'stage', 'D1', '글로벌 공급망 이슈나 환율 변동 등 거시 경제 리스크에 대한 대응 시나리오가 있다.', 3.5, 'M'),
(gen_random_uuid(), 'stage', 'D2', '사내 벤처나 신사업 팀을 통해 기존 사업을 파괴할 혁신적인 문제를 탐구한다.', 4, 'M'),
(gen_random_uuid(), 'stage', 'D2', '지역 사회나 국가적 과제 해결에 기여하며 존경받는 기업으로서 문제를 해결한다.', 3.5, 'M'),
(gen_random_uuid(), 'stage', 'D2', '고객의 라이프스타일 변화에 맞춰 오래된 문제 정의를 재해석(Re-framing)하고 있다.', 3.5, 'M'),
(gen_random_uuid(), 'stage', 'D3', '오랜 업력으로 쌓인 데이터와 노하우를 자산화하여 새로운 부가가치를 창출한다.', 4, 'M'),
(gen_random_uuid(), 'stage', 'D3', '헤리티지(전통)와 혁신을 결합하여 기존 고객과 신규 고객을 동시에 만족시킨다.', 3.5, 'M'),
(gen_random_uuid(), 'stage', 'D3', '경쟁사가 모방할 수 없는 압도적인 품질 격차나 특허 포트폴리오를 유지하고 있다.', 4.5, 'M'),
(gen_random_uuid(), 'stage', 'D4', '차세대 리더 육성 및 승계 계획(Succession Plan)이 체계적으로 준비되어 있다.', 4.5, 'M'),
(gen_random_uuid(), 'stage', 'D4', '조직의 관료화를 막고 애자일(Agile)한 혁신 문화를 이식하기 위한 제도가 있다.', 4, 'M'),
(gen_random_uuid(), 'stage', 'D4', '노무, 세무, 법무 등 컴플라이언스 이슈를 전담하는 전문 조직이나 시스템이 있다.', 4, 'M'),
(gen_random_uuid(), 'stage', 'D5', '스마트 팩토리, AI 도입 등 디지털 트랜스포메이션(DX)을 통해 생산성을 높인다.', 4.5, 'M'),
(gen_random_uuid(), 'stage', 'D5', '기존 기술의 수명 주기를 파악하고, 차세대 핵심 기술(Next Tech)에 투자한다.', 4, 'M'),
(gen_random_uuid(), 'stage', 'D5', '기술 유출 방지 및 핵심 인력 보안을 위한 고도화된 보안 시스템이 작동한다.', 3.5, 'M'),
(gen_random_uuid(), 'stage', 'D6', '안정적인 현금 창출원(Cash Cow)을 바탕으로 신사업(Star)에 과감히 재투자한다.', 4.5, 'M'),
(gen_random_uuid(), 'stage', 'D6', '불필요한 비용을 제거하기 위한 전사적 자원 관리(ERP) 및 원가 혁신이 이루어진다.', 4, 'M'),
(gen_random_uuid(), 'stage', 'D6', 'IPO(상장), 기업 매각, 분사 등 기업 가치 제고를 위한 출구 전략을 검토한다.', 3.5, 'M'),
(gen_random_uuid(), 'stage', 'D7', 'M&A나 CVC(기업형 벤처캐피털) 활동을 통해 외부의 혁신 동력을 수혈한다.', 4, 'M'),
(gen_random_uuid(), 'stage', 'D7', 'ESG 경영 보고서를 발간하고, 이를 통해 기업 신뢰도와 가치를 높이고 있다.', 3.5, 'M'),
(gen_random_uuid(), 'stage', 'D7', '10년, 20년 뒤에도 기업이 존속하기 위한 중장기 비전이 전 직원에게 공유된다.', 4, 'M'),
(gen_random_uuid(), 'industry', 'D1', '공급자와 수요자 중 누구를 먼저 모을 것인지 ''닭과 달걀'' 해결 전략이 있다.', 3.5, 'I'),
(gen_random_uuid(), 'industry', 'D1', '초기 거점 시장(Niche)을 장악한 뒤 대중 시장으로 넓혀갈 구체적인 확장 시나리오가 있다.', 3.5, 'I'),
(gen_random_uuid(), 'industry', 'D1', '경쟁 서비스 대비 우리의 진입 시점이 너무 빠르거나 늦지 않았음을 데이터로 입증할 수 있다.', 3, 'I'),
(gen_random_uuid(), 'industry', 'D2', '사용자가 앱을 실행하는 과정에서 이탈하는 ''병목 구간''을 로그 데이터로 파악했다.', 4, 'I'),
(gen_random_uuid(), 'industry', 'D2', '우리의 솔루션이 없으면 사용자가 얼마나 큰 비용이나 시간을 낭비하게 되는지 수치화했다.', 3.5, 'I'),
(gen_random_uuid(), 'industry', 'D2', '기존 대안(엑셀, 수기 등)이 해결하지 못하는 ''결정적인 기능적 결핍''을 기술적으로 정의했다.', 4, 'I'),
(gen_random_uuid(), 'industry', 'D3', '사용자가 늘어날수록 서비스 가치가 기하급수적으로 커지는 ''네트워크 효과''가 설계되어 있다.', 4.5, 'I'),
(gen_random_uuid(), 'industry', 'D3', '경쟁사가 쉽게 따라 할 수 없는 독점적 데이터나 알고리즘을 보유하고 있다.', 4, 'I'),
(gen_random_uuid(), 'industry', 'D3', '고객이 쌓아둔 데이터나 설정 때문에 이탈하기 어려운 ''락인(Lock-in)'' 요소가 있다.', 4, 'I'),
(gen_random_uuid(), 'industry', 'D4', '기획/디자인/개발이 하나의 팀으로 움직여 제품을 수정하는 애자일(Agile) 문화가 있다.', 4, 'I'),
(gen_random_uuid(), 'industry', 'D4', '기술적 의사결정을 주도하고 개발팀을 리딩할 수 있는 CTO급 리더나 파트너가 있다.', 4.5, 'I'),
(gen_random_uuid(), 'industry', 'D4', '서비스 장애 시 24시간 대응하거나 보안 이슈를 처리할 운영 인력 및 매뉴얼이 있다.', 3.5, 'I'),
(gen_random_uuid(), 'industry', 'D5', '트래픽 폭주 시 서버가 다운되지 않도록 오토 스케일링 등 클라우드 아키텍처가 설계되었다.', 4, 'I'),
(gen_random_uuid(), 'industry', 'D5', '개인정보보호법 등 관련 법규를 준수하기 위한 데이터 암호화 및 보안 조치가 적용되었다.', 3.5, 'I'),
(gen_random_uuid(), 'industry', 'D5', '우리가 사용하는 기술 스택이 최신 트렌드에 맞고 개발자 채용에 용이한가?', 3, 'I'),
(gen_random_uuid(), 'industry', 'D6', '무료 사용자(Free)를 유료(Paid)로 전환시킬 명확한 과금 트리거가 있다.', 4.5, 'I'),
(gen_random_uuid(), 'industry', 'D6', '고객 1명을 데려오는 비용(CAC)보다 생애 가치(LTV)가 3배 이상 높거나 개선 중이다.', 4.5, 'I'),
(gen_random_uuid(), 'industry', 'D6', '구독 취소 방지를 위한 해지 방어(Churn Prevention) 프로세스가 설계되어 있다.', 3.5, 'I'),
(gen_random_uuid(), 'industry', 'D7', '단순 설치 수가 아닌, 활성 사용자(MAU/DAU)와 체류 시간을 핵심 지표로 관리한다.', 4, 'I'),
(gen_random_uuid(), 'industry', 'D7', '국내 시장을 넘어 글로벌 런칭을 위한 다국어 지원 및 현지화 계획이 있다.', 3.5, 'I'),
(gen_random_uuid(), 'industry', 'D7', '외부 서비스와 연동할 수 있는 API를 공개하거나 플랫폼 생태계를 구축할 계획이 있다.', 3, 'I'),
(gen_random_uuid(), 'industry', 'D1', 'B2B, B2C 등 우리 제품 특성에 가장 적합한 1차 유통 채널과 진입 전략이 확정되었다.', 3.5, 'H'),
(gen_random_uuid(), 'industry', 'D1', '제품의 부피와 무게를 고려할 때, 물류비와 보관비가 시장 경쟁력을 해치지 않는다.', 3, 'H'),
(gen_random_uuid(), 'industry', 'D1', '시장 진입 필수 인증(KC, CE, FDA 등) 획득 요건과 비용/기간을 파악했다.', 4, 'H'),
(gen_random_uuid(), 'industry', 'D2', '기존 경쟁 제품들의 품질 불량이나 AS 문제를 분석하여 개선점을 반영했다.', 3.5, 'H'),
(gen_random_uuid(), 'industry', 'D2', '제품 사용 시 발생할 수 있는 안전사고나 오작동 리스크를 사전에 정의하고 대비했다.', 4.5, 'H'),
(gen_random_uuid(), 'industry', 'D2', '고객이 제품을 개봉하고 설치하는 과정(Unboxing)에서의 사용자 경험을 최적화했다.', 3, 'H'),
(gen_random_uuid(), 'industry', 'D3', '기능뿐만 아니라 디자인, 소재, 마감(Look & Feel)에서 경쟁사 대비 고급감을 준다.', 3.5, 'H'),
(gen_random_uuid(), 'industry', 'D3', '제품의 수명 주기를 고려하여 AS 및 부품 교체 서비스를 설계했다.', 4, 'H'),
(gen_random_uuid(), 'industry', 'D3', '경쟁 제품 대비 스펙(성능, 무게, 배터리 등)상 확실한 우위를 점하는 항목이 있다.', 3.5, 'H'),
(gen_random_uuid(), 'industry', 'D4', '공장 선정, 금형 제작, 생산 감리 등 제조 공정을 총괄할 전문 인력(PM)이 있다.', 4.5, 'H'),
(gen_random_uuid(), 'industry', 'D4', '불량 발생 시 원인을 규명하고 대처할 수 있는 QC(품질관리) 담당자나 시스템이 있다.', 4, 'H'),
(gen_random_uuid(), 'industry', 'D4', '원자재 공급처나 외주 공장과 긴밀한 협력 관계(SCM)를 유지하고 있다.', 3.5, 'H'),
(gen_random_uuid(), 'industry', 'D5', '양산을 위한 금형 설계, 시사출, T1/T2 테스트 일정이 수립되었다.', 4.5, 'H'),
(gen_random_uuid(), 'industry', 'D5', '핵심 부품의 단종이나 수급 불안정에 대비한 이원화된 공급망이 있다.', 4, 'H'),
(gen_random_uuid(), 'industry', 'D5', '생산성을 높이고 불량을 줄이기 위한 공정 자동화나 스마트 팩토리 도입을 검토했다.', 3, 'H'),
(gen_random_uuid(), 'industry', 'D6', '원자재비, 가공비, 물류비 등을 포함한 BOM 기반의 원가 분석이 완료되었다.', 4.5, 'H'),
(gen_random_uuid(), 'industry', 'D6', '유통 채널별 수수료를 제하고도 이익이 남는 적정 소비자가가 설정되었다.', 4, 'H'),
(gen_random_uuid(), 'industry', 'D6', '재고가 쌓이지 않고 현금이 돌게 하는 적정 재고 회전율 목표가 있다.', 3.5, 'H'),
(gen_random_uuid(), 'industry', 'D7', '국내 시장 포화 시 수출을 위한 해외 규격 인증 및 현지화 계획이 있다.', 3.5, 'H'),
(gen_random_uuid(), 'industry', 'D7', '단일 제품 의존도를 낮추기 위한 후속 모델이나 파생 상품 라인업이 기획되었다.', 3.5, 'H'),
(gen_random_uuid(), 'industry', 'D7', '생산량이 늘어날수록 단가가 떨어지는 규모의 경제 실현 시점을 예측하고 있다.', 4, 'H'),
(gen_random_uuid(), 'industry', 'D1', '입점 예정지의 유동 인구, 배후 세대수, 주 소비층을 분석하여 매출을 추정했다.', 4.5, 'L'),
(gen_random_uuid(), 'industry', 'D1', '인근 1km 내 경쟁 매장 대비 우리의 컨셉이나 메뉴가 차별화되는지 확인했다.', 3.5, 'L'),
(gen_random_uuid(), 'industry', 'D1', '날씨, 계절, 요일별 매출 편차를 고려한 영업 전략(피크타임 관리 등)이 있다.', 3, 'L'),
(gen_random_uuid(), 'industry', 'D2', '고객이 매장 입장부터 퇴장까지 겪는 대기 시간, 동선 불편을 최소화했다.', 4, 'L'),
(gen_random_uuid(), 'industry', 'D2', '메뉴의 맛이나 서비스 품질이 언제 방문해도 균일하도록 관리하고 있다.', 4.5, 'L'),
(gen_random_uuid(), 'industry', 'D2', '매장 방문 고객의 불만 사항을 즉시 해결하고 보상하는 매뉴얼이 있다.', 3.5, 'L'),
(gen_random_uuid(), 'industry', 'D3', '인테리어, 음악, 조명 등 오감(五感)을 만족시키는 공간 경험(VMD)을 제공한다.', 3.5, 'L'),
(gen_random_uuid(), 'industry', 'D3', '우리 매장만의 시그니처 메뉴나 서비스가 있어 멀리서도 찾아올 이유가 있다.', 4, 'L'),
(gen_random_uuid(), 'industry', 'D3', '고객을 기억하고 맞춤형 서비스를 제공하는 접객(Hospitality) 마인드가 갖춰져 있다.', 3.5, 'L'),
(gen_random_uuid(), 'industry', 'D4', '직원이 바뀌어도 서비스 품질이 유지되도록 표준 운영 매뉴얼(SOP)이 준비되었다.', 4, 'L'),
(gen_random_uuid(), 'industry', 'D4', '아르바이트생 및 직원에 대한 교육 훈련 및 동기 부여 프로그램이 있다.', 3.5, 'L'),
(gen_random_uuid(), 'industry', 'D4', '위생, 안전, 노무 등 매장 운영 관련 법적 규제를 준수하는 관리 체계가 있다.', 4.5, 'L'),
(gen_random_uuid(), 'industry', 'D5', '식자재나 소모품을 안정적이고 저렴하게 공급받을 거래처 네트워크가 있다.', 4, 'L'),
(gen_random_uuid(), 'industry', 'D5', '주문, 결제, 예약을 효율적으로 처리할 POS, 키오스크, 예약 앱 등을 도입했다.', 3, 'L'),
(gen_random_uuid(), 'industry', 'D5', '주방 동선이나 서비스 동선을 최적화하여 운영 효율(회전율)을 높이는 구조다.', 3.5, 'L'),
(gen_random_uuid(), 'industry', 'D6', '테이블 회전율, 객단가, 원가율(Food Cost) 등 핵심 수익 지표를 매일 관리한다.', 4.5, 'L'),
(gen_random_uuid(), 'industry', 'D6', '임대료, 인건비 등 고정비를 감당할 수 있는 손익분기점 매출을 명확히 안다.', 4, 'L'),
(gen_random_uuid(), 'industry', 'D6', '배달, 포장, 밀키트 등 오프라인 공간 제약을 넘는 추가 수익원이 있다.', 3, 'L'),
(gen_random_uuid(), 'industry', 'D7', '단골 고객을 관리하고 재방문을 유도할 멤버십이나 쿠폰 시스템이 작동한다.', 4, 'L'),
(gen_random_uuid(), 'industry', 'D7', '직영점 확장 또는 프랜차이즈 가맹 사업을 위한 표준화 모델 및 법적 준비가 되었다.', 3.5, 'L'),
(gen_random_uuid(), 'industry', 'D7', '지역 커뮤니티와의 상생이나 이벤트를 통해 로컬 브랜드로서의 입지를 다지고 있다.', 3, 'L'),
(gen_random_uuid(), 'industry', 'D1', '우리의 콘텐츠(캐릭터, 스토리)를 소비할 핵심 장르 시장과 팬덤 규모를 파악했다.', 3.5, 'CT'),
(gen_random_uuid(), 'industry', 'D1', '현재 유행하는 트렌드(Meme)와 부합하거나, 반대로 확실한 차별점이 있다.', 3, 'CT'),
(gen_random_uuid(), 'industry', 'D1', '콘텐츠를 유통할 최적의 플랫폼(유튜브, 웹툰, OTT 등)과 진입 전략이 있다.', 3.5, 'CT'),
(gen_random_uuid(), 'industry', 'D2', '기존 콘텐츠들이 채워주지 못하는 대중의 정서적 결핍이나 니즈를 건드리고 있다.', 4, 'CT'),
(gen_random_uuid(), 'industry', 'D2', '콘텐츠 소비자가 몰입을 방해받지 않도록 품질이나 주기(연재 등)를 관리한다.', 4, 'CT'),
(gen_random_uuid(), 'industry', 'D2', '팬들의 피드백이나 2차 창작 활동을 모니터링하며 소통하고 있다.', 3.5, 'CT'),
(gen_random_uuid(), 'industry', 'D3', '다른 콘텐츠와 구별되는 우리만의 독창적인 세계관이나 캐릭터성이 있다.', 4.5, 'CT'),
(gen_random_uuid(), 'industry', 'D3', '한 번 보면 잊혀지지 않는 시각적 스타일(Art Style)이나 훅(Hook)이 있다.', 3.5, 'CT'),
(gen_random_uuid(), 'industry', 'D3', '시간이 지나도 가치가 유지되거나 쌓이는 아카이브형(Stock) 콘텐츠인가?', 3, 'CT'),
(gen_random_uuid(), 'industry', 'D4', '창작의 퀄리티를 유지하면서 지속적으로 생산할 수 있는 제작 파이프라인이 있다.', 4, 'CT'),
(gen_random_uuid(), 'industry', 'D4', '저작권 관리, 계약, 정산 등 비즈니스 영역을 담당할 매니저나 파트너가 있다.', 3.5, 'CT'),
(gen_random_uuid(), 'industry', 'D4', '팬덤을 관리하고 커뮤니티를 운영할 마케팅/운영 역량을 갖추고 있다.', 3.5, 'CT'),
(gen_random_uuid(), 'industry', 'D5', '창작물의 무단 도용을 막고 소유권을 증명할 저작권 등록 및 IP 보호 조치를 취했다.', 4.5, 'CT'),
(gen_random_uuid(), 'industry', 'D5', '콘텐츠 제작 효율을 높이기 위한 디지털 툴(AI, SW 등)이나 장비를 활용하고 있다.', 3, 'CT'),
(gen_random_uuid(), 'industry', 'D5', '원본 데이터를 안전하게 보관하고 관리하는 디지털 자산 관리(DAM) 체계가 있다.', 3.5, 'CT'),
(gen_random_uuid(), 'industry', 'D6', '하나의 IP를 웹툰, 영상, 굿즈 등으로 확장하는 OSMU 전략이 있다.', 4, 'CT'),
(gen_random_uuid(), 'industry', 'D6', '광고, 유료 판매, 라이선싱, 굿즈 등 수익 모델(BM)이 다각화되어 있다.', 4, 'CT'),
(gen_random_uuid(), 'industry', 'D6', '크라우드 펀딩이나 후원을 통해 제작비를 사전 조달할 수 있는 팬덤이 있다.', 3.5, 'CT'),
(gen_random_uuid(), 'industry', 'D7', '번역, 자막, 더빙 등을 통해 글로벌 플랫폼으로 진출할 계획이 있다.', 3.5, 'CT'),
(gen_random_uuid(), 'industry', 'D7', '우리 IP와 시너지를 낼 수 있는 타 브랜드와의 콜라보레이션 계획이 있다.', 3.5, 'CT'),
(gen_random_uuid(), 'industry', 'D7', '콘텐츠를 넘어 게임, 테마파크, 메타버스 등 이종 산업으로의 확장 가능성이 있다.', 3, 'CT'),
(gen_random_uuid(), 'esg', 'D1', '우리 사업이 돈을 버는 과정에서 환경 파괴나 불공정 등 사회적 논란을 일으킬 요소는 없는지 점검했다.', 3.5, 'P'),
(gen_random_uuid(), 'esg', 'D2', '우리가 해결하려는 문제가 단순 불편함을 넘어, 사회적 약자나 환경에 기여할 수 있는 공익적 가치를 담고 있는가?', 4, 'P'),
(gen_random_uuid(), 'esg', 'D3', '제품 소재나 서비스 과정에서 친환경적 요소나 윤리적 가치를 차별화 포인트로 내세울 수 있는가?', 3.5, 'P'),
(gen_random_uuid(), 'esg', 'D4', '대표자인 나는 투명한 자금 집행과 약속 이행을 최우선으로 여기는 기업 윤리 의식을 확고히 가지고 있는가?', 4.5, 'P'),
(gen_random_uuid(), 'esg', 'D5', '고객의 개인정보를 무리하게 수집하거나, 기술을 악용하지 않겠다는 기술 윤리 원칙을 세웠는가?', 3.5, 'P'),
(gen_random_uuid(), 'esg', 'D6', '협력사나 파트너에게 무리한 단가 인하를 요구하지 않고 정당한 대가를 지불하는 수익 구조를 설계했는가?', 3.5, 'P'),
(gen_random_uuid(), 'esg', 'D7', '단기적인 이익보다 우리 회사가 사회에 미칠 **장기적인 긍정적 영향력(Impact)**을 목표로 삼고 있는가?', 4, 'P'),
(gen_random_uuid(), 'esg', 'D1', '우리 브랜드가 지향하는 가치(친환경, 공정함 등)에 대해 실제 고객들이 긍정적으로 반응하고 구매하는가?', 3.5, 'E'),
(gen_random_uuid(), 'esg', 'D2', '고객의 불만이나 피해 발생 시, 이를 숨기지 않고 투명하게 공개하고 책임지는 프로세스가 작동하는가?', 4.5, 'E'),
(gen_random_uuid(), 'esg', 'D3', '제품 포장재를 줄이거나 디지털 탄소 발자국을 줄이는 등 실질적인 친환경 활동을 실천하고 있는가?', 3.5, 'E'),
(gen_random_uuid(), 'esg', 'D4', '근로계약서, 최저임금, 4대 보험 등 노동 관련 법규를 100% 준수하며 직원을 보호하고 있는가?', 4.5, 'E'),
(gen_random_uuid(), 'esg', 'D5', '서비스 운영 중 발생할 수 있는 데이터 유출 사고에 대비해 최소한의 보안 장치나 보험을 마련했는가?', 4, 'E'),
(gen_random_uuid(), 'esg', 'D6', '수익의 일부를 사회에 환원하거나, 비즈니스와 연계된 소규모 공헌 활동을 시작했는가?', 3, 'E'),
(gen_random_uuid(), 'esg', 'D7', '지역 사회나 커뮤니티와 소통하며 **''우리 동네에 필요한 기업''**이라는 평판을 쌓아가고 있는가?', 3.5, 'E'),
(gen_random_uuid(), 'esg', 'D1', '글로벌 ESG 트렌드나 규제(탄소국경세 등)가 우리 사업에 미칠 영향을 분석하고 선제적으로 대응하고 있는가?', 4, 'V'),
(gen_random_uuid(), 'esg', 'D2', '비즈니스 규모가 커질수록 사회적 문제 해결 효과도 함께 커지는 임팩트 비즈니스 모델이 작동하는가?', 4, 'V'),
(gen_random_uuid(), 'esg', 'D3', '친환경 인증, 사회적 기업 인증 등 공신력 있는 제3자 인증을 획득하여 신뢰도를 높였는가?', 3.5, 'V'),
(gen_random_uuid(), 'esg', 'D4', '성별, 나이, 학력에 차별 없는 채용과 다양성(Diversity)을 존중하는 조직 문화가 정착되어 있는가?', 3.5, 'V'),
(gen_random_uuid(), 'esg', 'D5', '데이터 센터 에너지 효율화나 공정 폐기물 감소 등 기술적/공학적 탄소 감축 노력을 하고 있는가?', 4, 'V'),
(gen_random_uuid(), 'esg', 'D6', '협력사의 ESG 리스크까지 관리하며, 공급망 전체의 지속 가능성을 높이는 상생 프로그램을 운영하는가?', 4, 'V'),
(gen_random_uuid(), 'esg', 'D7', '임팩트 투자자나 ESG 펀드로부터 투자를 유치하기 위한 ESG 성과 지표 관리 및 IR을 수행하는가?', 4.5, 'V'),
(gen_random_uuid(), 'esg', 'D1', 'RE100, UN SDGs 등 글로벌 이니셔티브에 동참하거나 이에 준하는 목표를 수립했는가?', 4, 'M'),
(gen_random_uuid(), 'esg', 'D2', '단순 기부를 넘어, 기업의 핵심 역량으로 사회 문제를 해결하는 CSV(공유가치창출) 프로젝트를 진행하는가?', 4, 'M'),
(gen_random_uuid(), 'esg', 'D3', '소비자의 알 권리를 위해 제품의 전 성분, 생산 과정, 환경 영향 등을 **투명하게 공개(Traceability)**하는가?', 3.5, 'M'),
(gen_random_uuid(), 'esg', 'D4', '이사회의 독립성을 보장하고, 주주의 권익을 보호하는 투명한 지배구조(Governance) 시스템을 갖췄는가?', 4.5, 'M'),
(gen_random_uuid(), 'esg', 'D5', '산업 재해 없는 안전한 일터를 만들기 위해 중대재해처벌법 등 안전보건 경영 체계를 완비했는가?', 4.5, 'M'),
(gen_random_uuid(), 'esg', 'D6', '발생한 수익을 R&D뿐만 아니라, 직원 복지 및 사회 환원 재원으로 재투자하는 비율을 정해두었는가?', 3.5, 'M'),
(gen_random_uuid(), 'esg', 'D7', '매년 지속가능경영 보고서를 발간하여 재무적/비재무적 성과를 대내외 이해관계자와 소통하는가?', 4, 'M');
