'use client'

import { useCallback, useEffect, useState } from 'react'
import Link from 'next/link'
import { BookOpen, Loader2 } from 'lucide-react'

type Engagement = { id: string; viewer_role: 'mentor' | 'company'; status: string; requested_specialty_codes?: string[] }
type Session = { id: string; engagement_id: string; viewer_role: 'mentor' | 'company'; starts_at: string; ends_at: string; mode: string; status: string; log?: { mentee_content?: string | null; institution_content?: string | null; mentee_visible?: boolean } | null }

export default function MentoringWorkspacePage() {
  const [engagements, setEngagements] = useState<Engagement[]>([])
  const [sessions, setSessions] = useState<Session[]>([])
  const [loading, setLoading] = useState(true)
  const [forms, setForms] = useState<Record<string, { menteeContent: string; institutionContent: string; menteeVisible: boolean }>>({})
  const load = useCallback(async () => { const response = await fetch('/api/mentoring/workspace', { cache: 'no-store' }); const result = await response.json(); if (response.ok) { setEngagements(result.engagements || []); setSessions(result.sessions || []) } setLoading(false) }, [])
  useEffect(() => { void Promise.resolve().then(load) }, [load])
  const save = async (session: Session) => { const form = forms[session.id] || { menteeContent: session.log?.mentee_content || '', institutionContent: session.log?.institution_content || '', menteeVisible: session.log?.mentee_visible ?? true }; const response = await fetch(`/api/mentoring/sessions/${encodeURIComponent(session.id)}/log`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const result = await response.json(); if (!response.ok) alert(result.error || '일지를 저장하지 못했습니다.'); else await load() }
  return <main className="min-h-screen bg-slate-50 px-5 py-12"><div className="mx-auto max-w-4xl"><div className="flex items-center justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-black"><BookOpen className="text-indigo-600" /> 멘토링 작업공간</h1><p className="mt-2 text-sm text-slate-500">일정과 역할별 공개 기록을 관리합니다.</p></div><Link href="/dashboard" className="text-sm font-semibold text-indigo-600">대시보드</Link></div>{loading ? <div className="flex justify-center p-20"><Loader2 className="animate-spin" /></div> : engagements.length === 0 ? <div className="mt-8 rounded-xl border bg-white p-8 text-center text-sm text-slate-500">진행 중인 멘토링이 없습니다.</div> : <div className="mt-8 space-y-5">{engagements.map((engagement) => <section key={engagement.id} className="rounded-2xl border bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold">{engagement.viewer_role === 'mentor' ? '멘토 담당 건' : '기업 멘토링'}</h2><p className="text-xs text-slate-400">{(engagement.requested_specialty_codes || []).join(', ')}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{engagement.status}</span></div><div className="mt-4 space-y-4">{sessions.filter((session) => session.engagement_id === engagement.id).map((session) => { const form = forms[session.id] || { menteeContent: session.log?.mentee_content || '', institutionContent: session.log?.institution_content || '', menteeVisible: session.log?.mentee_visible ?? true }; return <div key={session.id} className="rounded-xl border border-slate-100 bg-slate-50 p-4"><p className="text-sm font-semibold">{new Date(session.starts_at).toLocaleString()} ~ {new Date(session.ends_at).toLocaleTimeString()} · {session.mode}</p>{session.viewer_role === 'mentor' ? <div className="mt-4 grid gap-3"><textarea className="min-h-28 rounded-lg border bg-white p-3 text-sm" placeholder="기업(멘티)에게 공개할 기록" value={form.menteeContent} onChange={(event) => setForms({ ...forms, [session.id]: { ...form, menteeContent: event.target.value } })} /><textarea className="min-h-28 rounded-lg border bg-white p-3 text-sm" placeholder="기관 운영자용 기록" value={form.institutionContent} onChange={(event) => setForms({ ...forms, [session.id]: { ...form, institutionContent: event.target.value } })} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.menteeVisible} onChange={(event) => setForms({ ...forms, [session.id]: { ...form, menteeVisible: event.target.checked } })} /> 기업에 기업용 기록 공개</label><button className="rounded-lg bg-slate-900 py-2 text-sm font-bold text-white" onClick={() => void save(session)}>일지 저장</button></div> : session.log?.mentee_visible ? <div className="mt-3 whitespace-pre-wrap rounded-lg bg-white p-3 text-sm text-slate-700">{session.log.mentee_content}</div> : <p className="mt-3 text-sm text-slate-400">멘토가 기업에 공개하지 않은 기록입니다.</p>}</div>})}</div></section>)}</div>}</div></main>
}
